### ISSUE TITLE
Adjust light lava fog strength

### ISSUE THREAD

**Issue by ItsPasi** [LordEnder-Kitty/FireHud#3]
The current problem is that the lava fog adapts to render distance, so at 32 chunks it is barely even visible. An option to either manually  change this or make it independent from render distance (for example always have it at 2 chunks render distance) would be a possible solution and imporvement.

**Comment by LordEnder-Kitty** [comment]
I don't understand your issue. What settings are you using and could you perhaps provide screenshots of the problem you're experiencing?

**Comment by ItsPasi** [comment]
> I don't understand your issue. What settings are you using and could you perhaps provide screenshots of the problem you're experiencing?

Well, that the light lava fog option of your mod changes the fog appearance depending on the vanilla render distance. At 32 chunks this destroys the illusion of any fog being there and even at 16 chunks it is still very light.

[Example](https://imgur.com/a/nFILcbb)

**Comment by LordEnder-Kitty** [comment]
Oh, ok. I see. I always play the game on 8 render distance so I didn't know that it was dependent on render distance. 
I'm not immediately sure how to fix it but I will potentially try to fix that when I update to 1.21.
